#ifndef TEJASVINI_SHARED_PROTOCOL_VERSION_H_
#define TEJASVINI_SHARED_PROTOCOL_VERSION_H_

#define TEJASVINI_PROTOCOL_VERSION_MAJOR 1
#define TEJASVINI_PROTOCOL_VERSION_MINOR 0
#define TEJASVINI_PROTOCOL_VERSION 1
#define TEJASVINI_PROTOCOL_VERSION_STR "1.0"

#define TEJASVINI_FIRMWARE_VERSION "v1.1.0"

#endif // TEJASVINI_SHARED_PROTOCOL_VERSION_H_
